[package]
name = "rf-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rf-core = { workspace = true }
iced = { workspace = true }
log = { workspace = true }
